<?php
/**
 * Définition des textes éditables par page publique (hors accueil).
 * Utilisé par l'admin (formulaires) et le seed CMS.
 */

declare(strict_types=1);

/**
 * @return array<string, array{
 *   label: string,
 *   permission: string,
 *   public: string,
 *   sidebar: string,
 *   textes: array<string, array>,
 *   defauts: array<string, string>,
 *   liens?: list<array{label: string, href: string}>
 * }>
 */
function cms_page_textes_defs(): array
{
    return [
        'a-propos' => [
            'label' => 'À propos',
            'permission' => 'a-propos',
            'public' => 'a-propos',
            'sidebar' => 'a-propos',
            'textes' => [
                'a-propos_mission_kicker' => ['section' => 'Mission', 'label' => 'Accroche', 'court' => true],
                'a-propos_mission_titre' => ['section' => 'Mission', 'label' => 'Titre', 'court' => true],
                'a-propos_mission_texte' => ['section' => 'Mission', 'label' => 'Texte'],
                'a-propos_mission_image' => ['section' => 'Mission', 'label' => 'Photo', 'media' => true],
                'a-propos_historique_kicker' => ['section' => 'Historique', 'label' => 'Accroche', 'court' => true, 'aide' => 'La chronologie se gère dans Contenu → Chronologie (groupe a-propos).'],
                'a-propos_historique_titre' => ['section' => 'Historique', 'label' => 'Titre', 'court' => true],
                'a-propos_direction_titre' => ['section' => 'Mot de la Direction', 'label' => 'Titre', 'court' => true],
                'a-propos_direction_photo' => ['section' => 'Mot de la Direction', 'label' => 'Photo', 'media' => true],
                'a-propos_direction' => ['section' => 'Mot de la Direction', 'label' => 'Texte (paragraphes séparés par une ligne vide)'],
                'a-propos_direction_signature' => ['section' => 'Mot de la Direction', 'label' => 'Signature', 'court' => true],
                'a-propos_enseignants_kicker' => ['section' => 'Corps enseignant', 'label' => 'Accroche', 'court' => true, 'aide' => 'Les 3 cartes se gèrent dans Contenu → Cartes (groupe a-propos-enseignants).'],
                'a-propos_enseignants_titre' => ['section' => 'Corps enseignant', 'label' => 'Titre', 'court' => true],
                'a-propos_enseignants_intro' => ['section' => 'Corps enseignant', 'label' => 'Texte d\'introduction'],
            ],
            'defauts' => [
                'a-propos_mission_kicker' => 'Notre mission',
                'a-propos_mission_titre' => "Former les talents qui développent l'Afrique",
                'a-propos_mission_texte' => "« Donner une formation de haut niveau adaptée au contexte africain et du monde contemporain afin de mettre à la disposition du marché » les compétences dont les entreprises ont besoin, et mobiliser les ressources intellectuelles pour le développement économique du continent.",
                'a-propos_mission_image' => 'campus/immeuble-iat.jpg',
                'a-propos_historique_kicker' => 'Historique',
                'a-propos_historique_titre' => 'Plus de 25 ans de croissance continue',
                'a-propos_direction_titre' => 'Le mot de la Direction',
                'a-propos_direction_photo' => 'fondateur-hamadou-hamidou.jpg',
                'a-propos_direction' => "Depuis 1999, l'Institut Africain de Technologie poursuit une seule ambition : offrir à la jeunesse nigérienne et africaine une formation à la hauteur de son potentiel. Nos quatre valeurs — l'excellence, la qualité, la transparence et l'ouverture au monde — ne sont pas des slogans : elles se lisent dans nos accréditations CAMES, dans nos laboratoires, dans les carrières de nos 30 000 diplômés.\n\nChoisir l'IAT, c'est rejoindre une institution qui investit continuellement dans ses infrastructures, son corps enseignant et ses partenariats internationaux, pour que chaque étudiant reparte avec bien plus qu'un diplôme : un métier, une méthode et un réseau.",
                'a-propos_direction_signature' => "M. Hamadou Hamidou — Fondateur de l'IAT Niger",
                'a-propos_enseignants_kicker' => 'Corps enseignant',
                'a-propos_enseignants_titre' => '36 enseignants-chercheurs de rang A',
                'a-propos_enseignants_intro' => 'Les Masters professionnels et le Master de Recherche sont animés par des enseignants-chercheurs de rang A — professeurs titulaires du CAMES, professeurs agrégés et maîtres de conférences.',
            ],
            'liens' => [
                ['label' => 'Valeurs (cartes)', 'href' => 'admin/contenu.php?type=carte&groupe=a-propos-valeurs'],
                ['label' => 'Statistiques', 'href' => 'admin/contenu.php?type=stat&groupe=a-propos'],
                ['label' => 'Chronologie', 'href' => 'admin/contenu.php?type=timeline&groupe=a-propos'],
                ['label' => 'Cartes enseignants', 'href' => 'admin/contenu.php?type=carte&groupe=a-propos-enseignants'],
            ],
        ],
        'admission' => [
            'label' => 'Admission',
            'permission' => 'admission',
            'public' => 'admission',
            'sidebar' => 'admission',
            'textes' => [
                'admission_conditions_kicker' => ['section' => "Conditions d'accès", 'label' => 'Accroche', 'court' => true, 'aide' => 'Le tableau reprend les niveaux (Formations → Niveaux). Les étapes se gèrent dans Contenu → Cartes (admission-etapes).'],
                'admission_conditions_titre' => ['section' => "Conditions d'accès", 'label' => 'Titre', 'court' => true],
                'admission_conditions_caption' => ['section' => "Conditions d'accès", 'label' => 'Note sous le tableau'],
                'admission_form_kicker' => ['section' => 'Préinscription', 'label' => 'Accroche', 'court' => true],
                'admission_form_titre' => ['section' => 'Préinscription', 'label' => 'Titre', 'court' => true],
                'admission_form_lead' => ['section' => 'Préinscription', 'label' => 'Texte d\'introduction'],
                'admission_form_success' => ['section' => 'Préinscription', 'label' => 'Message de succès'],
                'admission_form_btn' => ['section' => 'Préinscription', 'label' => 'Bouton d\'envoi', 'court' => true],
                'admission_form_privacy' => ['section' => 'Préinscription', 'label' => 'Mention confidentialité'],
                'admission_doc_kicker' => ['section' => 'Documentation', 'label' => 'Accroche', 'court' => true],
                'admission_doc_titre' => ['section' => 'Documentation', 'label' => 'Titre', 'court' => true],
                'admission_doc_lead' => ['section' => 'Documentation', 'label' => 'Texte'],
                'admission_doc_btn1' => ['section' => 'Documentation', 'label' => 'Bouton 1 (dépliant PDF)', 'court' => true],
                'admission_doc_btn2' => ['section' => 'Documentation', 'label' => 'Bouton 2 (brochure)', 'court' => true],
                'admission_doc_btn3' => ['section' => 'Documentation', 'label' => 'Bouton 3 (tous les documents)', 'court' => true],
                'admission_doc_image' => ['section' => 'Documentation', 'label' => 'Image', 'media' => true],
            ],
            'defauts' => [
                'admission_conditions_kicker' => "Conditions d'accès",
                'admission_conditions_titre' => 'Les conditions par niveau',
                'admission_conditions_caption' => "Dossier commun : extrait d'acte de naissance, certificat de nationalité, dernier bulletin ou diplôme. Master de Recherche : voir les pièces spécifiques.",
                'admission_form_kicker' => 'Préinscription en ligne',
                'admission_form_titre' => 'Déposez votre préinscription',
                'admission_form_lead' => 'Gratuite et sans engagement — la scolarité vous rappelle pour finaliser votre dossier.',
                'admission_form_success' => 'Préinscription enregistrée ! Merci pour votre confiance. Notre équipe scolarité vous contactera sous 48 h ouvrées au numéro indiqué.',
                'admission_form_btn' => 'Envoyer ma préinscription',
                'admission_form_privacy' => "Vos données restent confidentielles et ne servent qu'au traitement de votre candidature.",
                'admission_doc_kicker' => 'Documentation',
                'admission_doc_titre' => 'Brochure officielle 2025-2026',
                'admission_doc_lead' => "Retrouvez l'ensemble des filières, conditions et contacts dans la brochure officielle de l'institut, à télécharger et partager.",
                'admission_doc_btn1' => 'Dépliant & modalités de paiement (PDF)',
                'admission_doc_btn2' => 'Brochure 2025-2026',
                'admission_doc_btn3' => 'Tous les documents',
                'admission_doc_image' => 'brochure-2025-2026.jpg',
            ],
            'liens' => [
                ['label' => 'Étapes d\'admission', 'href' => 'admin/contenu.php?type=carte&groupe=admission-etapes'],
                ['label' => 'Niveaux (tableau)', 'href' => 'admin/formations.php?onglet=niveaux'],
                ['label' => 'Préinscriptions reçues', 'href' => 'admin/preinscriptions.php'],
            ],
        ],
        'vie-etudiante' => [
            'label' => 'Vie étudiante',
            'permission' => 'vie-etudiante',
            'public' => 'vie-etudiante',
            'sidebar' => 'vie-etudiante',
            'textes' => [
                'vie-etudiante_bde_kicker' => ['section' => 'Bureau Des Étudiants', 'label' => 'Accroche', 'court' => true, 'aide' => 'Les 3 cartes BDE se gèrent dans Contenu → Cartes (vie-etudiante-bde).'],
                'vie-etudiante_bde_titre' => ['section' => 'Bureau Des Étudiants', 'label' => 'Titre', 'court' => true],
                'vie-etudiante_bde_lead' => ['section' => 'Bureau Des Étudiants', 'label' => 'Texte d\'introduction'],
                'vie-etudiante_club_kicker' => ['section' => 'Clubs', 'label' => 'Accroche', 'court' => true],
                'vie-etudiante_club_titre' => ['section' => 'Clubs', 'label' => 'Titre', 'court' => true],
                'vie-etudiante_club_ppf' => ['section' => 'Clubs', 'label' => 'Texte Club PPF'],
                'vie-etudiante_club_image' => ['section' => 'Clubs', 'label' => 'Photo', 'media' => true],
                'vie-etudiante_club_btn' => ['section' => 'Clubs', 'label' => 'Texte du bouton', 'court' => true],
                'vie-etudiante_alumni_kicker' => ['section' => 'Alumni', 'label' => 'Accroche', 'court' => true, 'aide' => 'Les membres du bureau se gèrent dans Contenu → Alumni.'],
                'vie-etudiante_alumni_titre' => ['section' => 'Alumni', 'label' => 'Titre', 'court' => true],
                'vie-etudiante_alumni_intro' => ['section' => 'Alumni', 'label' => 'Texte d\'introduction'],
                'vie-etudiante_alumni_caption' => ['section' => 'Alumni', 'label' => 'Note sous les cartes'],
            ],
            'defauts' => [
                'vie-etudiante_bde_kicker' => 'Bureau Des Étudiants',
                'vie-etudiante_bde_titre' => 'Le BDE, moteur de la vie du campus',
                'vie-etudiante_bde_lead' => "Le BDE s'engage à « défendre les intérêts matériels et moraux de ses camarades dans le respect des textes de l'établissement », en cohérence avec la vision de l'IAT : promouvoir les futurs leaders.",
                'vie-etudiante_club_kicker' => 'Clubs étudiants',
                'vie-etudiante_club_titre' => 'Le Club PPF : des étudiantes actrices du changement',
                'vie-etudiante_club_ppf' => "Le Club PPF (Participation Politique des Femmes) mène des campagnes de sensibilisation sur le campus et au-delà. Il a récemment reçu du matériel de sonorisation pour amplifier ses actions, et co-organise des journées de sensibilisation contre les violences basées sur le genre.",
                'vie-etudiante_club_image' => 'actualites/club-ppf-appui.jpg',
                'vie-etudiante_club_btn' => 'Suivre leurs actions',
                'vie-etudiante_alumni_kicker' => 'Alumni',
                'vie-etudiante_alumni_titre' => "L'Amicale des Anciens : un réseau qui ouvre des portes",
                'vie-etudiante_alumni_intro' => "Les anciens de l'IAT occupent des postes dans les ministères (Finances, Transport, DGI), le secteur privé (consulting, télécoms), le secteur public et l'entrepreneuriat.",
                'vie-etudiante_alumni_caption' => "Le bureau compte également des secrétaires chargés de la communication et de l'organisation, des commissaires aux comptes et un trésorier adjoint.",
            ],
            'liens' => [
                ['label' => 'Cartes BDE', 'href' => 'admin/contenu.php?type=carte&groupe=vie-etudiante-bde'],
                ['label' => 'Alumni', 'href' => 'admin/contenu.php?type=alumni&groupe=vie-etudiante'],
            ],
        ],
        'csp-algoza' => [
            'label' => 'CSP Algoza',
            'permission' => 'csp',
            'public' => 'csp-algoza',
            'sidebar' => 'csp',
            'textes' => [
                'csp-algoza_atouts_kicker' => ['section' => 'Atouts', 'label' => 'Accroche', 'court' => true, 'aide' => 'Les 4 cartes atouts et les tarifs se gèrent dans Contenu.'],
                'csp-algoza_atouts_titre' => ['section' => 'Atouts', 'label' => 'Titre', 'court' => true],
                'csp-algoza_intro' => ['section' => 'Atouts', 'label' => 'Texte d\'introduction'],
                'csp-algoza_niveaux_kicker' => ['section' => 'Niveaux', 'label' => 'Accroche', 'court' => true],
                'csp-algoza_niveaux_titre' => ['section' => 'Niveaux', 'label' => 'Titre', 'court' => true],
                'csp-algoza_card_mat_titre' => ['section' => 'Niveaux', 'label' => 'Titre carte Maternelle & Primaire', 'court' => true],
                'csp-algoza_niveau_mat_primaire' => ['section' => 'Niveaux', 'label' => 'Texte Maternelle & Primaire'],
                'csp-algoza_card_col_titre' => ['section' => 'Niveaux', 'label' => 'Titre carte Collège & Lycée', 'court' => true],
                'csp-algoza_niveau_college_lycee' => ['section' => 'Niveaux', 'label' => 'Texte Collège & Lycée'],
                'csp-algoza_reductions_label' => ['section' => 'Niveaux', 'label' => 'Libellé réductions', 'court' => true],
                'csp-algoza_reductions' => ['section' => 'Niveaux', 'label' => 'Texte réductions'],
                'csp-algoza_cta_titre' => ['section' => 'Appel à l\'action', 'label' => 'Titre', 'court' => true],
                'csp-algoza_cta_lead' => ['section' => 'Appel à l\'action', 'label' => 'Texte'],
                'csp-algoza_cta_btn' => ['section' => 'Appel à l\'action', 'label' => 'Bouton', 'court' => true],
            ],
            'defauts' => [
                'csp-algoza_atouts_kicker' => 'Nos atouts',
                'csp-algoza_atouts_titre' => 'Un enseignement enrichi, des classes à taille humaine',
                'csp-algoza_intro' => "Le curriculum national nigérien, enrichi de cours solides en anglais et en informatique, dans une approche pédagogique multiculturelle où chaque enfant peut s'épanouir.",
                'csp-algoza_niveaux_kicker' => 'Les niveaux',
                'csp-algoza_niveaux_titre' => 'De la Petite Section à la Terminale',
                'csp-algoza_card_mat_titre' => 'Maternelle & Primaire',
                'csp-algoza_niveau_mat_primaire' => "Petite Section (2-3 ans), Moyenne Section (3-4 ans), Grande Section (4-5 ans), puis Cours d'Initiation (5-6 ans) et tout le cycle primaire. L'anglais commence dès le CI.",
                'csp-algoza_card_col_titre' => 'Collège & Lycée',
                'csp-algoza_niveau_college_lycee' => "Programme de l'État nigérien enrichi. Au lycée, trois orientations : les séries A, C et D. Uniforme : robe/chemise blanche, jupe/pantalon bleu marine.",
                'csp-algoza_reductions_label' => 'Réductions familles nombreuses :',
                'csp-algoza_reductions' => 'Des réductions sont accordées aux familles ayant plus de trois enfants inscrits au CSP Algoza.',
                'csp-algoza_cta_titre' => 'Inscrivez votre enfant au CSP Algoza',
                'csp-algoza_cta_lead' => "Contactez-nous pour connaître les disponibilités et planifier une visite de l'école.",
                'csp-algoza_cta_btn' => 'Nous contacter',
            ],
            'liens' => [
                ['label' => 'Cartes atouts', 'href' => 'admin/contenu.php?type=carte&groupe=csp-algoza-atouts'],
                ['label' => 'Tarifs', 'href' => 'admin/contenu.php?type=tarif&groupe=csp-algoza'],
            ],
        ],
        'partenaires' => [
            'label' => 'Partenaires',
            'permission' => 'partenaires',
            'public' => 'partenaires',
            'sidebar' => 'partenaires',
            'textes' => [
                'partenaires_cta_titre' => ['section' => 'Appel à partenariats', 'label' => 'Titre', 'court' => true, 'aide' => 'La liste des logos se gère dans Contenu → Partenaires.'],
                'partenaires_cta_lead' => ['section' => 'Appel à partenariats', 'label' => 'Texte'],
                'partenaires_cta_btn' => ['section' => 'Appel à partenariats', 'label' => 'Bouton', 'court' => true],
            ],
            'defauts' => [
                'partenaires_cta_titre' => "Devenir partenaire de l'IAT",
                'partenaires_cta_lead' => 'Entreprise, institution ou université : construisons ensemble des programmes qui servent la jeunesse africaine.',
                'partenaires_cta_btn' => 'Proposer un partenariat',
            ],
            'liens' => [
                ['label' => 'Liste des partenaires', 'href' => 'admin/contenu.php?type=partenaire'],
            ],
        ],
        'faq' => [
            'label' => 'FAQ',
            'permission' => 'faq',
            'public' => 'faq',
            'sidebar' => 'faq',
            'textes' => [
                'faq_cta_lead' => ['section' => 'Bas de page', 'label' => 'Texte avant le bouton', 'court' => true, 'aide' => 'Les questions/réponses se gèrent dans Contenu → FAQ.'],
                'faq_cta_btn' => ['section' => 'Bas de page', 'label' => 'Bouton', 'court' => true],
            ],
            'defauts' => [
                'faq_cta_lead' => 'Vous ne trouvez pas votre réponse ?',
                'faq_cta_btn' => 'Contactez-nous',
            ],
            'liens' => [
                ['label' => 'Questions / réponses', 'href' => 'admin/contenu.php?type=faq'],
            ],
        ],
        'contact' => [
            'label' => 'Contact',
            'permission' => 'parametres',
            'public' => 'contact',
            'sidebar' => 'parametres',
            'textes' => [
                'contact_coords_kicker' => ['section' => 'Coordonnées', 'label' => 'Accroche', 'court' => true, 'aide' => 'Adresse, téléphones et e-mail se gèrent dans Paramètres du site.'],
                'contact_coords_titre' => ['section' => 'Coordonnées', 'label' => 'Titre', 'court' => true],
                'contact_form_titre' => ['section' => 'Formulaire', 'label' => 'Titre du formulaire', 'court' => true],
                'contact_form_btn' => ['section' => 'Formulaire', 'label' => 'Bouton d\'envoi', 'court' => true],
                'contact_form_success' => ['section' => 'Formulaire', 'label' => 'Message de succès'],
                'contact_sujets' => ['section' => 'Formulaire', 'label' => 'Sujets du menu déroulant (un par ligne)', 'liste' => true],
                'contact_map_kicker' => ['section' => 'Carte', 'label' => 'Accroche', 'court' => true],
                'contact_map_link' => ['section' => 'Carte', 'label' => 'Lien « ouvrir la carte »', 'court' => true],
            ],
            'defauts' => [
                'contact_coords_kicker' => 'Nos coordonnées',
                'contact_coords_titre' => 'Rendez-nous visite ou appelez-nous',
                'contact_form_titre' => 'Envoyez-nous un message',
                'contact_form_btn' => 'Envoyer le message',
                'contact_form_success' => 'Message envoyé ! Merci de nous avoir écrit — nous vous répondrons dans les meilleurs délais.',
                'contact_sujets' => "Demande d'information\nInscription / Admission\nCSP Algoza\nPartenariat\nPresse & médias\nAutre",
                'contact_map_kicker' => 'Localisation',
                'contact_map_link' => 'Ouvrir la carte en grand',
            ],
            'liens' => [
                ['label' => 'Coordonnées (paramètres)', 'href' => 'admin/parametres.php'],
            ],
        ],
        'telechargements' => [
            'label' => 'Téléchargements',
            'permission' => 'documents',
            'public' => 'telechargements',
            'sidebar' => 'documents',
            'textes' => [
                'telechargements_dl_btn' => ['section' => 'Documents', 'label' => 'Libellé du bouton « Télécharger »', 'court' => true, 'aide' => 'La liste des fichiers se gère dans Contenu → Documents.'],
                'telechargements_paiement_kicker' => ['section' => 'Modalités de paiement', 'label' => 'Accroche', 'court' => true],
                'telechargements_paiement_titre' => ['section' => 'Modalités de paiement', 'label' => 'Titre', 'court' => true],
                'telechargements_paiement_texte' => ['section' => 'Modalités de paiement', 'label' => 'Texte'],
                'telechargements_paiement_items' => ['section' => 'Modalités de paiement', 'label' => 'Points (un par ligne)', 'liste' => true],
                'telechargements_paiement_btn1' => ['section' => 'Modalités de paiement', 'label' => 'Bouton 1', 'court' => true],
                'telechargements_paiement_btn2' => ['section' => 'Modalités de paiement', 'label' => 'Bouton 2 (téléphone)', 'court' => true],
                'telechargements_paiement_btn3' => ['section' => 'Modalités de paiement', 'label' => 'Bouton 3', 'court' => true],
            ],
            'defauts' => [
                'telechargements_dl_btn' => 'Télécharger',
                'telechargements_paiement_kicker' => 'Modalités de paiement',
                'telechargements_paiement_titre' => 'Comment régler les frais de scolarité ?',
                'telechargements_paiement_texte' => 'Les modalités de paiement officielles (montants par filière, échéanciers et facilités) sont détaillées dans le dépliant 2026-2027. Pour toute question ou situation particulière, le service scolarité vous accompagne.',
                'telechargements_paiement_items' => "Paiement au service scolarité du campus (rond-point Gadafawa, Yantala)\nÉchéanciers détaillés par niveau dans le dépliant officiel\nRéductions familles nombreuses au CSP Algoza (3 inscrits et plus)",
                'telechargements_paiement_btn1' => 'Dépliant & modalités (PDF)',
                'telechargements_paiement_btn2' => 'Scolarité',
                'telechargements_paiement_btn3' => 'Poser une question',
            ],
            'liens' => [
                ['label' => 'Documents', 'href' => 'admin/contenu.php?type=document'],
            ],
        ],
        'web-tv' => [
            'label' => 'WEB TV',
            'permission' => 'web-tv',
            'public' => 'web-tv',
            'sidebar' => 'web-tv',
            'textes' => [
                'web-tv_footer_caption' => ['section' => 'Bas de page', 'label' => 'Texte sous la grille', 'aide' => 'Les vidéos se gèrent dans Contenu → WEB TV.'],
                'web-tv_vues_label' => ['section' => 'Bas de page', 'label' => 'Libellé après le nombre de vues', 'court' => true],
            ],
            'defauts' => [
                'web-tv_footer_caption' => "Les vidéos s'ouvrent dans le lecteur de la WEB TV IAT. Suivez-nous aussi sur Facebook.",
                'web-tv_vues_label' => 'vues',
            ],
            'liens' => [
                ['label' => 'Vidéos', 'href' => 'admin/contenu.php?type=video'],
            ],
        ],
        'formations' => [
            'label' => 'Formations',
            'permission' => 'formations',
            'public' => 'formations',
            'sidebar' => 'formations',
            'textes' => [
                'formations_hub_card_link' => ['section' => 'Page hub', 'label' => 'Lien sur les cartes de niveau', 'court' => true, 'aide' => 'Les niveaux et filières se gèrent dans Formations.'],
                'formations_overview_kicker' => ['section' => 'Page hub', 'label' => 'Accroche « vue d\'ensemble »', 'court' => true],
                'formations_overview_titre' => ['section' => 'Page hub', 'label' => 'Titre « vue d\'ensemble »', 'court' => true],
                'formations_overview_btn' => ['section' => 'Page hub', 'label' => 'Bouton admission', 'court' => true],
                'formations_tertiaire_kicker' => ['section' => 'Pages niveaux', 'label' => 'Accroche filières tertiaires', 'court' => true],
                'formations_tertiaire_titre' => ['section' => 'Pages niveaux', 'label' => 'Titre filières tertiaires', 'court' => true],
                'formations_industriel_kicker' => ['section' => 'Pages niveaux', 'label' => 'Accroche filières industrielles', 'court' => true],
                'formations_industriel_titre' => ['section' => 'Pages niveaux', 'label' => 'Titre filières industrielles', 'court' => true],
                'formations_debouches_label' => ['section' => 'Pages niveaux', 'label' => 'Libellé « Débouchés »', 'court' => true],
                'formations_fiche_btn' => ['section' => 'Pages niveaux', 'label' => 'Bouton fiche complète', 'court' => true],
                'formations_cta_preinscription' => ['section' => 'Pages niveaux', 'label' => 'Bouton préinscription', 'court' => true],
                'formations_doctorat_essec_titre' => ['section' => 'Doctorat', 'label' => 'Titre partenariat ESSEC', 'court' => true],
                'formations_doctorat_essec_texte' => ['section' => 'Doctorat', 'label' => 'Texte partenariat ESSEC'],
                'formations_doctorat_essec_items' => ['section' => 'Doctorat', 'label' => 'Points partenariat (un par ligne)', 'liste' => true],
                'formations_doctorat_ecole_titre' => ['section' => 'Doctorat', 'label' => 'Titre École Doctorale', 'court' => true],
                'formations_doctorat_ecole_texte' => ['section' => 'Doctorat', 'label' => 'Texte École Doctorale'],
                'formations_doctorat_ecole_items' => ['section' => 'Doctorat', 'label' => 'Domaines (un par ligne)', 'liste' => true],
                'formations_doctorat_contacts' => ['section' => 'Doctorat', 'label' => 'Points de contact'],
            ],
            'defauts' => [
                'formations_hub_card_link' => 'Voir les filières',
                'formations_overview_kicker' => "Vue d'ensemble",
                'formations_overview_titre' => "Les 28 filières de l'IAT",
                'formations_overview_btn' => "Conditions d'admission",
                'formations_tertiaire_kicker' => 'Filières tertiaires',
                'formations_tertiaire_titre' => 'Gestion, commerce & services',
                'formations_industriel_kicker' => 'Filières industrielles',
                'formations_industriel_titre' => 'Ingénierie, technologies & industrie',
                'formations_debouches_label' => 'Débouchés',
                'formations_fiche_btn' => 'Fiche complète',
                'formations_cta_preinscription' => 'Déposer ma préinscription',
                'formations_doctorat_essec_titre' => 'Le partenariat ESSEC — Université de Douala',
                'formations_doctorat_essec_texte' => "Le partenariat vise à « accompagner les activités de formation et de recherche de l'IAT dans le domaine des Sciences économiques et de Gestion ».",
                'formations_doctorat_essec_items' => "Formation académique : Licence, Master et Doctorat\nFormation professionnelle continue\nMobilité des enseignants et des étudiants\nProjets de recherche et événements scientifiques",
                'formations_doctorat_ecole_titre' => "L'École Doctorale ESSEC",
                'formations_doctorat_ecole_texte' => "Après le Master de Recherche, poursuivez en thèse dans l'un des quatre domaines de l'École Doctorale :",
                'formations_doctorat_ecole_items' => "Business Economics\nManagement des organisations\nScience Juridique\nScience de l'ingénieur",
                'formations_doctorat_contacts' => 'Points de contact à l\'IAT : Cherifa Hamadou Hamidou · Ousseini Adamou Magagi · Bara Boubacar',
            ],
            'liens' => [
                ['label' => 'Niveaux & filières', 'href' => 'admin/formations.php'],
            ],
            'admin_file' => 'formations-textes.php',
        ],
    ];
}
